const products=[
{id:1,name:'No. 01 Atelier Coat',price:289,cat:'outerwear',img:'https://images.unsplash.com/photo-1544022613-e87ca75a784a?auto=format&fit=crop&w=900&q=85',desc:'A structured wool coat with a relaxed shoulder and clean concealed closure.'},
{id:2,name:'No. 07 Silk Shirt',price:145,cat:'tops',img:'https://images.unsplash.com/photo-1594633312681-425c7b97ccd1?auto=format&fit=crop&w=900&q=85',desc:'Fluid silk shirting cut with a long, elegant line.'},
{id:3,name:'No. 12 Pleated Trouser',price:175,cat:'bottoms',img:'https://images.unsplash.com/photo-1506629905607-d9a0e4d7c7c1?auto=format&fit=crop&w=900&q=85',desc:'Wide-leg tailoring with a single front pleat and considered drape.'},
{id:4,name:'No. 03 Cashmere Knit',price:198,cat:'tops',img:'https://images.unsplash.com/photo-1551488831-00ddcb6c6bd3?auto=format&fit=crop&w=900&q=85',desc:'Soft cashmere blend with a precise crew neckline.'},
{id:5,name:'No. 21 Leather Tote',price:220,cat:'accessories',img:'https://images.unsplash.com/photo-1548036328-c9fa89d128fa?auto=format&fit=crop&w=900&q=85',desc:'A structured everyday tote in full-grain leather.'},
{id:6,name:'No. 09 Long Dress',price:240,cat:'tops',img:'https://images.unsplash.com/photo-1539008835657-9e8e9680c956?auto=format&fit=crop&w=900&q=85',desc:'A long, minimal silhouette designed to move.'},
{id:7,name:'No. 15 Suede Jacket',price:325,cat:'outerwear',img:'https://images.unsplash.com/photo-1523398002811-999ca8dec234?auto=format&fit=crop&w=900&q=85',desc:'Supple suede with a softly structured profile.'},
{id:8,name:'No. 05 Signature Belt',price:85,cat:'accessories',img:'https://images.unsplash.com/photo-1624222247344-550fb60583dc?auto=format&fit=crop&w=900&q=85',desc:'Minimal hardware and vegetable-tanned leather.'},
{id:9,name:'No. 18 Tailored Short',price:130,cat:'bottoms',img:'https://images.unsplash.com/photo-1594633312681-425c7b97ccd1?auto=format&fit=crop&w=900&q=85',desc:'Relaxed tailoring for warmer days.'}
];
function card(p){return `<article class="product-card"><a href="product.html?id=${p.id}"><div class="product-img" style="background-image:url('${p.img}')"></div><div class="product-info"><div>${p.name}<br><small>${p.cat}</small></div><div>$${p.price}</div></div></a><button class="quick" onclick="addToCart(${p.id})">Add to bag</button></article>`}
function renderProducts(list,el){if(el)el.innerHTML=list.map(card).join('')}
renderProducts(products.slice(0,4),document.getElementById('home-products'));
const shop=document.getElementById('shop-products'); if(shop){renderProducts(products,shop);document.querySelectorAll('.filter').forEach(b=>b.onclick=()=>{document.querySelectorAll('.filter').forEach(x=>x.classList.remove('active'));b.classList.add('active');renderProducts(b.dataset.filter==='all'?products:products.filter(p=>p.cat===b.dataset.filter),shop)})}
function addToCart(id){let cart=JSON.parse(localStorage.getItem('luxoraCart')||'[]');cart.push(id);localStorage.setItem('luxoraCart',JSON.stringify(cart));updateCount();alert('Added to your bag.')}
function updateCount(){let c=JSON.parse(localStorage.getItem('luxoraCart')||'[]');document.querySelectorAll('.bag-count').forEach(x=>x.textContent=c.length)}
updateCount();
const pp=document.getElementById('product-page');if(pp){let id=new URLSearchParams(location.search).get('id')||1,p=products.find(x=>x.id==id)||products[0];pp.innerHTML=`<div class="product-layout"><div class="product-main-img" style="background-image:url('${p.img}')"></div><div class="product-details"><p class="eyebrow">${p.cat} / LUXORA</p><h1>${p.name}</h1><div class="product-price">$${p.price}</div><p>${p.desc}</p><div class="sizes"><button class="size">XS</button><button class="size">S</button><button class="size">M</button><button class="size">L</button><button class="size">XL</button></div><button class="add" onclick="addToCart(${p.id})">Add to bag — $${p.price}</button><div class="details-line">Details + composition</div><div class="details-line">Shipping & returns</div></div></div>`}
const cartEl=document.getElementById('cart-content');if(cartEl){let ids=JSON.parse(localStorage.getItem('luxoraCart')||'[]');if(!ids.length){cartEl.innerHTML='<div class="empty"><h2>Your bag is quiet.</h2><p>There is nothing here yet.</p><a class="btn dark" href="shop.html" style="margin-top:25px">Continue shopping</a></div>'}else{let items=ids.map(id=>products.find(p=>p.id==id)).filter(Boolean),total=items.reduce((s,p)=>s+p.price,0);cartEl.innerHTML=`<div class="cart-wrap"><div>${items.map(p=>`<div class="cart-item"><img src="${p.img}"><div><strong>${p.name}</strong><p style="margin-top:8px;opacity:.55">$${p.price}</p></div></div>`).join('')}</div><aside class="cart-summary"><div><span>Subtotal</span><strong>$${total}</strong></div><div><span>Shipping</span><span>Complimentary</span></div><button class="add" onclick="alert('Demo checkout — connect your payment provider here.')">Checkout</button><button class="text-link" style="border:0;background:none;cursor:pointer" onclick="localStorage.removeItem('luxoraCart');location.reload()">Clear bag</button></aside></div>`}}
document.querySelectorAll('.menu').forEach(b=>b.onclick=()=>{let n=document.querySelector('.nav nav');n.style.display=n.style.display==='flex'?'none':'flex';n.style.position='absolute';n.style.top='70px';n.style.left='0';n.style.right='0';n.style.padding='25px';n.style.background='#f4f1eb';n.style.flexDirection='column'});
